### ISSUE TITLE
New TOML field: user-visible application name

### ISSUE THREAD

**Issue by igrr** [espressif/esp-launchpad#42]
Currently application names are stored as TOML table names. This forces us to use hyphens and underscores in app names, which doesn't look very natural. For example, we would like to use "display (esp-box-lite, IDF v5.1.1)" instead of "display-esp-box-lite-v5_1_1". To solve this, we could add another key in the application table, storing the name to show to the user. If the field is not specified, Launchpad would fall back to the table name.

**Comment by igrr** [comment]
Although I might be wrong about spaces not being allowed... this TOML seems to validate fine on https://www.toml-lint.com/:
```toml
esp_toml_version = 1.0
firmware_images_url = "<URL to your firmware images directory>"
supported_apps = ["YOUR FIRMWARE APP NAME"]
["YOUR FIRMWARE APP NAME"]
chipsets = ["ESP32"]
image.esp32 = "SINGLE_BIN_FOR_ESP32.bin"
```
